// Five languages. Nothing else in the game stores a sentence, so switching
// re-reads the whole screen, including the epitaph on the death card.

export const LANGS = ['vi', 'en', 'ja', 'ko', 'zh'];
export const LABEL = { vi: 'VI', en: 'EN', ja: '日本語', ko: '한국어', zh: '中文' };

let current = 'vi';

export function setLang(code) {
  current = LANGS.includes(code) ? code : 'vi';
  return current;
}
export const langNow = () => current;
export function nextLang() {
  return LANGS[(LANGS.indexOf(current) + 1) % LANGS.length];
}

const WORDS = {
  vi: {
    title: 'NGƯỜI GÁC ĐÈN',
    boss: 'NGƯỜI GÁC ĐÈN',
    you: 'HIỆP SĨ',
    attempt: 'lần thứ {n}',
    essence: 'TINH CHẤT',
    dropped: 'rơi ở đây',
    fallen: 'ĐÃ NGÃ XUỐNG',
    victory: 'HẠ GỤC',
    retry: 'THỬ LẠI',
    enter: 'BƯỚC VÀO',
    rest: 'NGHỈ BÊN LỬA',
    vigour: 'SINH LỰC',
    endurance: 'THỂ LỰC',
    strength: 'SỨC MẠNH',
    flasks: 'BÌNH THUỐC',
    max: 'HẾT CẤP',
    cost: '{n}',
    'hint.move': 'A D · di chuyển',
    'hint.roll': 'PHÍM CÁCH · lăn (lúc lăn không bị đánh trúng)',
    'hint.attack': 'J hoặc chạm · chém · bấm tiếp để ra đòn hai',
    'hint.block': 'K · đỡ (tốn thể lực)',
    'hint.drink': 'L · uống thuốc',
    'tip.tell': 'Vệt đỏ dưới đất = chỗ sắp bị đánh. Lăn ra khỏi đó.',
    'tip.punish': 'Đánh xong nó đứng đơ một nhịp. Đó là lúc của bạn.',
    'tip.lunge': 'Đòn lao tới thì lăn NGƯỢC VÀO nó, đừng chạy lùi.',
    'tip.stam': 'Hết thể lực thì đỡ cũng vỡ. Đừng bấm liên tục.',
    'tip.phase': 'Nó mở đèn. Từ giờ ra đòn xong nó hồi nhanh hơn.',
    'tip.essence': 'Tinh chất rơi chỗ bạn ngã. Đi qua để nhặt lại.',
    'body.lost': 'Chết không mất gì vĩnh viễn. Tinh chất nằm ở chỗ bạn ngã — lần sau đi qua nhặt lại là tiêu được ngay.',
    'body.won': 'Đèn tắt. Bạn đã đọc được nó.',
    'body.rest': 'Đổi tinh chất lấy sức. Càng ngã nhiều, càng mạnh.',
    'stat.attempts': 'SỐ LẦN',
    'stat.best': 'SÂU NHẤT',
  },
  en: {
    title: 'THE LANTERN WARDEN',
    boss: 'THE LANTERN WARDEN',
    you: 'KNIGHT',
    attempt: 'attempt {n}',
    essence: 'ESSENCE',
    dropped: 'dropped here',
    fallen: 'YOU DIED',
    victory: 'WARDEN FELLED',
    retry: 'TRY AGAIN',
    enter: 'ENTER',
    rest: 'REST AT THE FIRE',
    vigour: 'VIGOUR',
    endurance: 'ENDURANCE',
    strength: 'STRENGTH',
    flasks: 'FLASKS',
    max: 'MAX',
    cost: '{n}',
    'hint.move': 'A D · move',
    'hint.roll': 'SPACE · roll (you cannot be hit mid-roll)',
    'hint.attack': 'J or tap · swing · press again for the second hit',
    'hint.block': 'K · block (costs stamina)',
    'hint.drink': 'L · drink',
    'tip.tell': 'The red mark on the ground is where it will hit. Roll out of it.',
    'tip.punish': 'After it swings it is stuck for a beat. That beat is yours.',
    'tip.lunge': 'Roll INTO the lunge, not away from it.',
    'tip.stam': 'An empty stamina bar breaks your guard. Do not hold everything.',
    'tip.phase': 'The lantern is open. It recovers faster now.',
    'tip.essence': 'Your essence is lying where you fell. Walk over it.',
    'body.lost': 'Nothing is lost for good. Your essence waits where you fell — walk over it next time and it is yours to spend.',
    'body.won': 'The lantern is out. You read it.',
    'body.rest': 'Spend essence on being harder to kill. Every death pays for the next try.',
    'stat.attempts': 'ATTEMPTS',
    'stat.best': 'DEEPEST',
  },
  ja: {
    title: '灯守り',
    boss: '灯守り',
    you: '騎士',
    attempt: '{n}回目',
    essence: '精',
    dropped: 'ここに落とした',
    fallen: '死亡',
    victory: '討伐',
    retry: 'もう一度',
    enter: '進む',
    rest: '篝火で休む',
    vigour: '生命力',
    endurance: '持久力',
    strength: '筋力',
    flasks: '聖水',
    max: '最大',
    cost: '{n}',
    'hint.move': 'A D · 移動',
    'hint.roll': 'スペース · 転がる（無敵時間あり）',
    'hint.attack': 'J またはタップ · 斬る · もう一度で二撃目',
    'hint.block': 'K · 受け（持久力を使う）',
    'hint.drink': 'L · 飲む',
    'tip.tell': '地面の赤い印が攻撃範囲。そこから転がり出る。',
    'tip.punish': '攻撃の後に隙ができる。そこが好機。',
    'tip.lunge': '突進は下がらず、懐へ転がり込む。',
    'tip.stam': '持久力が尽きると受けが崩れる。押しっぱなしにしない。',
    'tip.phase': '灯が開いた。隙が短くなる。',
    'tip.essence': '倒れた場所に精が残っている。拾いに行く。',
    'body.lost': '永久に失うものはない。精は倒れた場所にある。次に拾えばそのまま使える。',
    'body.won': '灯が消えた。読み切った。',
    'body.rest': '精を強さに換える。死ぬたびに次が楽になる。',
    'stat.attempts': '挑戦',
    'stat.best': '最深',
  },
  ko: {
    title: '등불지기',
    boss: '등불지기',
    you: '기사',
    attempt: '{n}번째',
    essence: '정수',
    dropped: '여기에 떨어뜨림',
    fallen: '사망',
    victory: '토벌',
    retry: '다시',
    enter: '들어가기',
    rest: '화톳불에서 쉬기',
    vigour: '체력',
    endurance: '지구력',
    strength: '근력',
    flasks: '물약',
    max: '최대',
    cost: '{n}',
    'hint.move': 'A D · 이동',
    'hint.roll': '스페이스 · 구르기 (구르는 중엔 맞지 않음)',
    'hint.attack': 'J 또는 탭 · 베기 · 한 번 더 누르면 2타',
    'hint.block': 'K · 막기 (지구력 소모)',
    'hint.drink': 'L · 마시기',
    'tip.tell': '바닥의 붉은 표시가 공격 범위다. 굴러서 벗어나라.',
    'tip.punish': '공격 뒤에는 빈틈이 생긴다. 그때가 기회다.',
    'tip.lunge': '돌진은 물러나지 말고 안쪽으로 굴러 들어가라.',
    'tip.stam': '지구력이 바닥나면 막기가 깨진다. 계속 누르지 마라.',
    'tip.phase': '등불이 열렸다. 이제 회복이 빨라진다.',
    'tip.essence': '쓰러진 자리에 정수가 남아 있다. 밟고 지나가라.',
    'body.lost': '영원히 잃는 것은 없다. 정수는 쓰러진 자리에 있고, 다시 주우면 바로 쓸 수 있다.',
    'body.won': '등불이 꺼졌다. 끝까지 읽어냈다.',
    'body.rest': '정수를 힘으로 바꾼다. 죽을수록 다음이 쉬워진다.',
    'stat.attempts': '시도',
    'stat.best': '최고',
  },
  zh: {
    title: '提灯守夜人',
    boss: '提灯守夜人',
    you: '骑士',
    attempt: '第 {n} 次',
    essence: '精魂',
    dropped: '掉在这里',
    fallen: '你死了',
    victory: '已讨伐',
    retry: '再来',
    enter: '进入',
    rest: '在篝火旁休息',
    vigour: '生命',
    endurance: '耐力',
    strength: '力量',
    flasks: '药瓶',
    max: '满级',
    cost: '{n}',
    'hint.move': 'A D · 移动',
    'hint.roll': '空格 · 翻滚（翻滚中无敌）',
    'hint.attack': 'J 或点击 · 挥击 · 再按一次接第二段',
    'hint.block': 'K · 格挡（消耗耐力）',
    'hint.drink': 'L · 喝药',
    'tip.tell': '地上的红痕就是它要打的地方。滚出去。',
    'tip.punish': '它挥完会僵一下，那一下是你的。',
    'tip.lunge': '冲刺不要往后跑，往它身上滚。',
    'tip.stam': '耐力见底格挡就会被破。别一直按着。',
    'tip.phase': '灯打开了。它的收招变快了。',
    'tip.essence': '精魂留在你倒下的地方。走过去捡回来。',
    'body.lost': '没有什么是永久失去的。精魂就在你倒下的地方，下次捡回来立刻就能用。',
    'body.won': '灯灭了。你读懂了它。',
    'body.rest': '把精魂换成活下去的本钱。死得越多，下一次越稳。',
    'stat.attempts': '次数',
    'stat.best': '最深',
  },
};

export function t(key, params = {}) {
  const table = WORDS[current] || WORDS.vi;
  const raw = table[key] ?? WORDS.en[key] ?? key;
  return raw.replace(/\{(\w+)\}/g, (_m, name) =>
    params[name] === undefined ? `{${name}}` : String(params[name]),
  );
}
